# Generated by Django 4.2.16 on 2024-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
